version: '3.8'

services:
  standalone-chrome:
    image: selenium/standalone-chrome:4.18.1-20240224
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5902:5900"
    shm_size: 2g
  
  video:
    image: selenium/video:ffmpeg-6.1-20240224
    volumes:
      - ./videos:/videos
  # standalone-edge:
  #   image: selenium/standalone-edge:4.18.1-20240224
  #   ports:
  #     - "4445:4444"
  #     - "7901:7900"
  #   shm_size: 2g

  # standalone-firefox:
  #   image: selenium/standalone-firefox:4.18.1-20240224
  #   ports:
  #     - "4446:4444"
  #     - "7902:7900"
  #   shm_size: 2g
