version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
  web:
    image: ghostqa/ghostqa:latest
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command:  pipenv run gunicorn ghostqa.wsgi -w 4 -b 0.0.0.0:8000 -t 1000000000
    environment:
      - SHARED_PATH=/automation-tests
      - SHARED_PERFORMACE_PATH=/tests/
    volumes:
      - ./app/media:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
      - /automation-tests:/automation-tests
      - /tests/performace:/tests/performace
    ports:
      - "8010:8000"
    depends_on:
      - db
