# Generated by Django 5.0.2 on 2024-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenarios_file",
                    models.FileField(upload_to="uploads/scenarios_file/"),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "client_reference_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
