# Generated by Django 5.0.2 on 2024-02-22 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cypress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestContainersRuns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=255, null=True)),
                ("container_status", models.CharField(max_length=255, null=True)),
                ("container_labels", models.CharField(max_length=255, null=True)),
                ("container_name", models.CharField(max_length=255, null=True)),
                ("container_short_id", models.CharField(max_length=255, null=True)),
                ("container_logs_str", models.TextField(null=True)),
                (
                    "ref",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("json", models.JSONField(null=True)),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cypress.testsuite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestArtifacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255, null=True)),
                ("files", models.FileField(upload_to="uploads/artifacts/")),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cypress.testsuite",
                    ),
                ),
                (
                    "container_runs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cypress.testcontainersruns",
                    ),
                ),
            ],
        ),
    ]
