# Generated by Django 5.0.2 on 2024-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cypress", "0003_alter_testartifacts_container_runs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuite",
            name="cypress_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
