# Generated by Django 5.0.2 on 2024-03-04 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerformaceTestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_file", models.FileField(upload_to="uploads/performace_tests/")),
                ("name", models.CharField(max_length=1000)),
                (
                    "client_reference_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=250, null=True)),
                ("jthreads", models.CharField(blank=True, max_length=250, null=True)),
                ("jrampup", models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestContainersRuns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=255, null=True)),
                ("container_status", models.CharField(max_length=255, null=True)),
                ("container_labels", models.CharField(max_length=255, null=True)),
                ("container_name", models.CharField(max_length=255, null=True)),
                ("container_short_id", models.CharField(max_length=255, null=True)),
                ("container_logs_str", models.TextField(null=True)),
                (
                    "ref",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("json", models.JSONField(null=True)),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_runs",
                        to="performace_test.performacetestsuite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestArtifacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255, null=True)),
                ("files", models.FileField(upload_to="uploads/performace_tests/")),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suite_artifacts",
                        to="performace_test.performacetestsuite",
                    ),
                ),
                (
                    "container_runs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs_artifacts",
                        to="performace_test.testcontainersruns",
                    ),
                ),
            ],
        ),
    ]
