# Generated by Django 5.0.3 on 2024-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performace_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JmeterTestConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.FileField(upload_to="uploads/performace_tests/")),
                ("total_number_of_users", models.CharField(max_length=1000)),
                (
                    "ramp_up_time",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "ramp_up_steps",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("jthreads", models.CharField(blank=True, max_length=250, null=True)),
                ("jrampup", models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="testcontainersruns",
            name="client_reference_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="testcontainersruns",
            name="test_file",
            field=models.FileField(
                null=True, upload_to="uploads/performace_tests/TestContainersRuns/"
            ),
        ),
    ]
