# Generated by Django 5.0.3 on 2024-03-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performace_test", "0003_remove_performacetestsuite_jrampup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "csv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="uploads/performance_tests/csv_file",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_data",
                        to="performace_test.performacetestsuite",
                    ),
                ),
            ],
        ),
    ]
