FROM cypress/included:cypress-13.6.6-node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1

WORKDIR /e2e
RUN cd /e2e
RUN npm install cypress-multi-reporters 
RUN npm install mochawesome mochawesome-merge mochawesome-report-generator